### ISSUE TITLE
Regarding the apk  file

### ISSUE THREAD

**Issue by nitin122** [abhi-r3v0/EVABS#6]
Sir the apk file present in the github repository is not  there evabs apk is not available please help regarding this . please help with the installation procedure in Genymotion also

**Comment by abhi-r3v0** [comment]
Hi,

The APK file has been moved to the releases section. You can find it [here](https://github.com/abhi-r3v0/EVABS/releases)

The installation procedure is same for device/emulators. Refer to [this](https://www.hawkspawn.com/blog/getting-started-with-evabs/) :)

Regards
